const data = {
    "component_details": {
        "components": [
            {
                "component_name": "DGL-About You",
                "FormData": {
                    "code": "absa_dgl",
                    "language_locale": "EN",
                    "dgl_first_name": "Appadu",
                    "dgl_last_name": "Neetish",
                    "dgl_gender": "Male",
                    "dgl_marital_status": "Single",
                    "dgl_country_of_birth": "Afghanistan",
                    "dgl_nationality": "Afghanistan",
                    "dgl_source_of_wealth": "Bonus",
                    "dgl_assets_you_own": "Vehicles",
                    "dgl_liabilities_you_have": "None",
                    "dgl_loc_residential_address_1": "2A AVE DE TULIP ST JEAN",
                    "dgl_loc_residential_address_2": "",
                    "dgl_loc_zip_code": "",
                    "dgl_loc_city": "QUATRE BORNES",
                    "dgl_loc_region": "Moka",
                    "dgl_loc_residence_status": "Tenant",
                    "dgl_correspondence_address": "Yes",
                    "dgl_loc_time_at_address_year": "3 years",
                    "dgl_loc_time_at_address_month": "2 months",
                    "dgl_gender_other": "",
                    "dgl_corr_residential_address_1": "",
                    "dgl_corr_residential_address_2": "",
                    "dgl_corr_zip_code": "",
                    "dgl_corr_city": "",
                    "dgl_corr_region": "",
                    "dgl_corr_residence_status": "",
                    "dgl_corr_time_at_address_year": "",
                    "dgl_corr_time_at_address_month": ""
                }
            },
            {
                "component_name": "DGL-Tell us about your job",
                "FormData": {
                    "code": "absa_dgl",
                    "language_locale": "EN",
                    "dgl_employer_name": "ABSA BANK LIMITED",
                    "dgl_employment_industry": "Aviation",
                    "dgl_your_occupation": "Manager",
                    "dgl_salary_credited_to": "Bank of  Baroda",
                    "dgl_account_number": "143035026",
                    "dgl_basic_value": "547",
                    "dgl_monthly_net_value": "59046",
                    "dgl_month_gross_value": "70",
                    "dgl_other_any_other_value": "1820",
                    "dgl_salary_account_to_absa": "Yes",
                    "dgl_basic_currency": "MUR",
                    "dgl_transport_allowance_currency": "MUR",
                    "dgl_transport_allowance_value": "32000",
                    "dgl_other_allowance_currency": "MUR",
                    "dgl_other_allowance_value": "12000",
                    "dgl_monthly_net_currency": "MUR",
                    "dgl_month_gross_currency": "MUR",
                    "dgl_other_any_other_currency": "MUR",
                    "dgl_your_occupation_other": ""
                }
            },
            {
                "component_name": "DGL-Loan Requirement",
                "FormData": {
                    "code": "absa_dgl",
                    "language_locale": "EN",
                    "dgl_purpose_of_loan": "Family",
                    "dgl_your_relationship": "Mother",
                    "dgl_mobile_no_of_referee": "+2301234567890",
                    "dgl_name_of_person": "Ahmed",
                    "dgl_loan_required_value": "675,793",
                    "dgl_repayment_period_value": "29",
                    "dgl_loan_required_currency": "MUR",
                    "dgl_repayment_period_months": "Months",
                    "dgl_purpose_of_loan_other": "",
                    "dgl_preferred_start_date_of_repayment": "2023-06-21T18:30:00.000Z"
                }
            },
            {
                "component_name": "DGL-Summary",
                "FormData": {
                    "code": "absa_dgl",
                    "language_locale": "EN",
                    "dgl_loan_tenure": "29 Months",
                    "dgl_monthly_repayment": "600 MUR",
                    "dgl_interest_rate": "15%",
                    "dgl_annualised_rate": "8.45%",
                    "dgl_one_time_processing_fee": "2000",
                    "dgl_applying_loan_amount": "1200",
                    "dgl_new_loan_requirement": "",
                    "dgl_buyback_loan_amount": "",
                    "dgl_loan_details": ""
                }
            },
            {
                "component_name": "DGL-Credit Life Insurance",
                "FormData": {
                    "code": "absa_dgl",
                    "language_locale": "EN",
                    "dgl_agreed_to_insurance_terms_conditions": "Yes",
                    "dgl_customer_info": {
                        "pkey_Customer_Id": "2",
                        "customer_Type": "1",
                        "customer_Title": "Mr",
                        "customer_Code": "1234",
                        "ciD_ref": null,
                        "ciD_ref_name": null,
                        "first_Name": "Smith",
                        "last_Name": "Adex",
                        "address": "Port Loius",
                        "city": "Port Loius",
                        "telephone_Number": "57166233",
                        "email": "sm123@gmail.com",
                        "account_Number": null,
                        "personal_Customer_Type": "1",
                        "personal_Customer_Title": "Mr",
                        "personal_Customer_Code": "1234",
                        "personal_First_Name": "Smith",
                        "personal_Last_Name": "Adex",
                        "personal_Address": "Port Loius",
                        "personal_Address_2": null,
                        "personal_City": "Port Loius",
                        "personal_Country_of_Residence": "Mauritius",
                        "personal_Gender": "Male",
                        "personal_Telephone_Number": "57166233",
                        "personal_Mobile_Number": "53666277",
                        "personal_Fax_Number": null,
                        "personal_Date_of_Birth": "1990-07-01",
                        "personal_Email": "sm123@gmail.com",
                        "occupation": "Web Developer",
                        "document_NIC_Passport_Number": "12334567",
                        "document_NIC": null,
                        "document_Incorporation_Number": null,
                        "document_BRN": null,
                        "document_VAT_Number": null,
                        "document_Valid_Driving_License": "false",
                        "document_Provisional_Driving_License": "false",
                        "document_License_Number": "12334567",
                        "document_Date_Issued": null,
                        "document_Employer": "InfiniTech",
                        "document_Marital_Status": "Single",
                        "document_Pref_Mode_of_Communication": "0",
                        "document_Occupation_Trade": null,
                        "document_Occupation_Class": null,
                        "document_US_Citizen": "No",
                        "isSameAsCustomerDetails": "true",
                        "customer_Status": "true",
                        "createdBy": "1",
                        "createdDate": "2020-12-01T12:48:55.236008",
                        "updatedBy": "9",
                        "updateDate": "2021-06-13T06:45:38.303135",
                        "isDeleted": "false",
                        "delete_Reason": null,
                        "deletedBy": null,
                        "deletedDate": null
                    },
                    "dgl_DTA_unSecured_data": {
                        "success": "true",
                        "newProposalId": "1042",
                        "FileName": "Smith__20220502054353482.xlsx",
                        "sendMail": "false",
                        "updateProposal": "Update",
                        "NIC_PID_Premium_Single": "14688",
                        "MUA_PID_Premium_Single": "14381"
                    },
                    "dgl_insurance_info": {
                        "id": "3",
                        "companyName": "National Insurance Company",
                        "premiumAmount": "14688"
                    },
                    "dgl_insurance_questions": {},
                    "dgl_medical_condition_suffering_from": "",
                    "dgl_health_treatment": "",
                    "dgl_date_of_last_symptoms": "",
                    "dgl_name_address_of_treating_doctor": ""
                }
            }
        ]
    },
    "form_application_id": 3397,
    "integradoc_process_id": null
}